version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf:ro
      - certs:/etc/letsencrypt
      - acme:/var/www/certbot

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - certs:/etc/letsencrypt
      - acme:/var/www/certbot

volumes:
  certs:
  acme:
